version: '3'

services:
  db:
    image: mysql:8.0.22
    container_name: my01
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: "8de"
      MYSQL_DB: "8dedb"
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/var/www/client
    depends_on: 
      - server
      - client

  client:
    image: node:18
    container_name: re01
    working_dir: /client
    command: bash -c "
        yarn install &&
        yarn build"
    # command: sh entrypoint.sh
    volumes:
      - ./client/:/client
    depends_on:
      - db
  
  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    container_name: dg01
    working_dir: /server
    command: bash -c "
        python3 manage.py makemigrations account &&
        python3 manage.py makemigrations playlist &&
        python3 manage.py makemigrations model &&
        python3 manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 server.wsgi:application -w 16 --threads 8 -t 300"
    # command: sh entrypoint.sh
    volumes:
      - ./server/:/server
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy