services:
  nginx:
    image:
      nginx:latest
    container_name:
      ng01
    ports:
      - "80:80"
    volumes:
      - .:/src/server
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - web
  
  web:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: dg01
    command: bash -c "
        cd ./server &&
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        gunicorn --bind 0.0.0.0:80 server.wsgi:application"
    volumes:
      - .:/src
    expose:
      - "8000"
    image: 
      8de
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    image: mysql:8.0.22
    container_name: my01
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "8de"
      MYSQL_DB: "8dedb"
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # interval: 1m30s
      timeout: 30s
      retries: 10
      # start_period: 30s